### PR TITLE
Allow arbitrary placement of accidentals

### PR DESCRIPTION
**Pull request by ghost**
Sometimes accidentals are placed after Roman numeral: `\markup \rN { Vs }` (see #2). This patch allows user to place accidentals either before or after note name/Roman numeral/figure. Tested on LilyPond 2.18.2.

### CODE REVIEW

**Comment by ghost** [comment]
> I think I just misread everything. I told you I'm fairly new to this :(

If you're new to git I recommend you to take a look at [GitHub Guides](https://guides.github.com/) for an introduction and [Pro Git Book](https://progit.org/) for an in-depth discussion of the subject.

> Please forgive any offense, just a momentary confusion on my part!

No problem. :ok_hand: 

> I will look through what you've suggested. It would be great if you have an example of this usage, b/c I've always seen the alteration before the RN.

Here's an example from Harmony and Voice Leading (Aldwell & Schachter), page 441:
lowered-third

**Comment by davidnalesnik** [comment]
On Mon, Dec 14, 2015 at 12:22 PM, mengele-chan notifications@github.com
wrote:

> Oh, sorry. I think I just misread everything. I told you I'm fairly new to
> this :(
> 
> If you're new to git I recommend you to take a look at GitHub Guides
> https://guides.github.com/ for an introduction and Pro Git Book
> https://progit.org/ for an in-depth discussion of the subject.

Thanks for the references!  It's mostly GitHub that's the problem.  I've
been working with git for awhile with LilyPond development, but only here
and there with Github.

> Please forgive any offense, just a momentary confusion on my part!
> 
> No problem. [image: :ok_hand:]
> 
> :)
> 
> I will look through what you've suggested. It would be great if you have
> an example of this usage, b/c I've always seen the alteration before the RN.
> 
> Here's an example from Harmony and Voice Leading (Aldwell & Schachter):
> [image: lowered-third]
> https://cloud.githubusercontent.com/assets/12159469/11789459/7528fba8-a28e-11e5-9de3-d1a2e5839011.png
> 
> Aha, I see.  I will need to check that book out.  I'm used to triad quality
> being at least partially indicated by the case of the numeral.
>  (Kostka/Payne, Gauldin, and Clendinning are the texts I've used and I own
> a few others that do it this way.)  I had Aldwell/Schachter for a semester,
> but I seem to have lost track of my copy....  I seem to remember that
> Piston's text also uses a capitals-only approach (though I don't imagine
> that that book is used at all anymore).

**Comment by davidnalesnik** [comment]
Trying this out, it looks like this will be a nice extension.

I wonder: would you ever have the situation where you have an accidental
before and after in this style of notation?  Something like bVIb, for
example?  The way the code works now, the first flat will be rendered,but
"f" will be returned for the second.

I could merge this pull request, and multiple alterations could be dealt
with later (as that will be more invasive).

[BTW, I will probably revise the comments at some point.  This function
isn't used anymore for figures.]

**Comment by sambivens** [comment]
It's rare, but that type of notation /does/ exist. It's typically found 
in more Schenkerian circles, but it would definitely be a nice feature 
(especially for teachers of chromatic harmony). For example, the second 
theme of the first movement of Mahler 2 is in E major. Compared to the 
global C minor, this would technically be { nIII n5 s }.

The opening movement of Waldstein is an example of the "friendlier" 
example we've been discussing: E major in C major is { III s }.

As an aside, my experience is that the Kostka/Payne is still very common 
in undergraduate American training. Gauldin is all but gone these days. 
Clendinning/Marvin is very popular, as is the Laitz (which is even 
popular in various foreign countries; I know schools in China use it, 
for instance). Aldwell/Schachter is still around, but the Laitz is often 
viewed as the descendant of that textbook tradition, so the latter is 
more popular. I don't know of any schools still using the Piston.

On 12/14/2015 03:22 PM, davidnalesnik wrote:

> Trying this out, it looks like this will be a nice extension.
> 
> I wonder: would you ever have the situation where you have an accidental
> before and after in this style of notation? Something like bVIb, for
> example? The way the code works now, the first flat will be rendered,but
> "f" will be returned for the second.
> 
> I could merge this pull request, and multiple alterations could be dealt
> with later (as that will be more invasive).
> 
> [BTW, I will probably revise the comments at some point. This function
> isn't used anymore for figures.]
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/davidnalesnik/lilypond-roman-numeral-tool/pull/3#issuecomment-164548457.

## 

Sam Bivens
Ph.D. Student, Music Theory
Eastman School of Music
Co-Editor, /Intégral/

**Comment by davidnalesnik** [comment]
On Mon, Dec 14, 2015 at 2:39 PM, Sam Bivens notifications@github.com
wrote:

> It's rare, but that type of notation /does/ exist. It's typically found
> in more Schenkerian circles, but it would definitely be a nice feature
> (especially for teachers of chromatic harmony). For example, the second
> theme of the first movement of Mahler 2 is in E major. Compared to the
> global C minor, this would technically be { nIII n5 s }.
> 
> Happily, this _mostly_ works.  I'd just need to admit "n" in
> figure-alteration and in make-figure-markup and this will work.  (The
> alignment of the figure column may be an issue, though.  Eventually,
> something more sophisticated than a right-aligned column will need to be
> used.)
> 
> The opening movement of Waldstein is an example of the "friendlier"
> example we've been discussing: E major in C major is { III s }.

The patch will handle that, but you will need to write { IIIs }
.

> As an aside, my experience is that the Kostka/Payne is still very common
> in undergraduate American training. Gauldin is all but gone these days.
> 
> Clendinning/Marvin is very popular, as is the Laitz (which is even
> popular in various foreign countries; I know schools in China use it,
> for instance). Aldwell/Schachter is still around, but the Laitz is often
> viewed as the descendant of that textbook tradition, so the latter is
> more popular. I don't know of any schools still using the Piston.

The Gauldin was used at IU for a year--1998, I think. A very nice book.
(Before that was K&P.)  The school I taught at most recently used K&P and
phased it out for the Clendinning a few years ago.  I own a review copy of
the Laitz  (one of the few perks of being an adjunct, but that's another
topic :)  )  Laitz does use the lower-case-for-minor notation.

**Comment by ghost** [comment]
> I wonder: would you ever have the situation where you have an accidental before and after in this style of notation? Something like bVIb, for example?

I never encountered such notation, but if I will, I'll inform you.

**Comment by ghost** [comment]
As promised, here's an excerpt from Harmony and Voice Leading (Aldwell & Schachter), page 589:
accidental-before-and-after-roman-numeral

**Pull request merged**
